config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks', 
    registrations:      'registrations', 
  }
  
  devise_scope :user do
    get 'users/password_changes' => 'registrations#password_changes'
  end
  
  # root to: "posts#index"
  root to: "posts#following_posts"
  get      '/users/:id', to: 'users#show', as: 'user'
  
  resources :posts, only: %i(index new create show destroy following_posts) do
    collection do
      get "following_posts"
    end
    resources :photos,   only: %i(create)
    resources :likes,    only: %i(create destroy)
    resources :comments, only: %i(create destroy)
  end
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :relationships, only: %i(create, destroy)
  resources :notifications, only: %i(index)
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts,    dependent: :destroy
  has_many :likes,    dependent: :destroy
  has_many :comments, dependent: :destroy
  
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship",  dependent: :destroy
  has_many :following, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships
  
  has_many :active_notifications,  class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
         :omniauthable
         
  validates :name,         presence: true, length: { maximum:  50 }
  validates :email,        presence: true, uniqueness: true
  validates :user_name,    presence: true, length: { maximum:  50 },  uniqueness: true
  validates :profile_text,                 length: { maximum: 500 }
  validates :website_url,                  length: { maximum: 500 }
  
  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    User.dummy_email(auth),
        password: Devise.friendly_token[0, 20]
      )
    end
    user
  end
  
  def update_without_current_password(params, *options)
      params.delete(:current_password)
  
      if params[:password].blank? && params[:password_confirmation].blank?
        params.delete(:password)
        params.delete(:password_confirmation)
      end

      result = update_attributes(params, *options)
      clean_up_passwords
      result
  end
  
  #フォローしているかを確認するメソッド
  def following?(user)
    following_relationships.find_by(following_id: user.id)
  end

  #フォローするときのメソッド
  def follow(user)
    following_relationships.create!(following_id: user.id)
  end

  #フォローを外すときのメソッド
  def unfollow(user)
    following_relationships.find_by(following_id: user.id).destroy
  end
  
  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
  
  private

    def self.dummy_email(auth)
      "#{auth.uid}-#{auth.provider}@example.com"
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_from :facebook
  end
 
  private
 
  def callback_from(provider)
    provider = provider.to_s
 
    @user = User.find_for_oauth(request.env['omniauth.auth'])
 
    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_current_user, only: %i(index)
  before_action :set_user, only: %i(show following followers)
  before_action :set_following, only: %i(index following followers)

  def index
    @users << @user
    @posts = Post.where(user_id: params[:id])
  end
  
  def show
    @posts = Post.includes(:photos, :user).where(user_id: params[:id]).order('created_at DESC').search(params[:search]).page(params[:page])
  end
  
  def edit
  end

  def following
    render 'show_follow'
  end
  
  def followers
    @users = @user.followers
    render 'show_follower'
  end
  
  private
    def set_following
      @users = @user.following
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user, url: relationships_path, method: :post, remote: true) do |f| %>
  <%= hidden_field_tag :following_id, @user.id %>
  <%= f.submit "フォローする", class: "btn btn-outline-secondary" %>
<% end %>

app/views/users/_follow_count.html.erb
<%= @user.followers.count %>

app/views/users/_follow_form.html.erb
<% if user_signed_in? && @user != current_user %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render "unfollow" %>
    <% else %>
      <%= render "follow" %>
    <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user, url: relationship_path(@user), method: :delete, remote: true) do |f| %>
  <%= f.submit "フォロー解除", class: "btn btn-outline-secondary" %>
<% end %>

app/views/users/edit.html.erb
user/edit

app/views/users/show.html.erb
<div class="container profile-wrap">
  <div class="row mb-3 text-center">
    <div class="col-md-4 ">
      <%= image_tag avatar_url(@user), class: "round-img" %>
    </div>
    <div class="col-md-8">
      <div class="row p-2 justify-content-center justify-content-md-start">
        <h1><%= @user.user_name %></h1>
        <% if @user == current_user %>
          <button type="button" class="setting" data-toggle="modal" data-target="#exampleModal"></button>
        <% end %>
      </div>
      
      <div class="row p-2 justify-content-center justify-content-md-start">
        <div class="follow mr-3">
          <%= link_to following_user_path(@user.id) do %>
            <h5 style="color: black;"><%= @user.following.count %>フォロー</h5>
          <% end %>
        </div>
        <div class="follower mr-3">
          <%= link_to followers_user_path(@user.id) do %>
            <h5 style="color: black;"><span class="follow" id="follow-count"><%= render 'follow_count' %></span>フォロワー</h5>
          <% end %>
        </div>
      </div>
        
        <div>
          <%= render "follow_form" %>
        </div>
        
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">設定</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">×</span>
                </button>
              </div>
              <div class="list-group text-center">
                <%= link_to "プロフィールを編集", edit_user_registration_path, class: "list-group-item list-group-item-action" %>
                <%= link_to "サインアウト", destroy_user_session_path, method: :delete, class: "list-group-item list-group-item-action" %>
                <%= link_to "キャンセル", "#", class: "list-group-item list-group-item-action", "data-dismiss": "modal" %>
              </div>
            </div>
          </div>
        </div>
    </div>
  </div>
  <div class="row p-2">
    <div class="col-md text-center">
      <p>
        <%= @user.profile_text %>
      </p>
    </div>
  </div>
</div>

<div class="row px-3 ">
  <div class="col-md-12">
    投稿数:<%= @user.posts.count %>
  </div>
</div>

<%= render 'posts/post' %>

app/views/users/show_follow.html.erb
<p class="p-3">
  <%= "フォローしているユーザーはいません" if @user.following.count == 0 %>
</p>
<% @user.following.each do |following| %>
  <%= link_to user_path(following.id), class: "black-color no-text-decoration",title: following.name do %>
    <div class="row mt-5">
      <div class="col-md-2 p-2">
        <%= image_tag avatar_url(following), class: "round-img" %>
      </div>
      <div class="col-md-10 p-2">
        <p><strong><%= following.name %></strong></p>
        <p><%= following.profile_text%></p>
      </div>
    </div>
  <% end %>
<% end %>
  

app/views/users/show_follower.html.erb
<p class="p-3">
  <%= "フォローされているユーザーはいません。" if @user.followers.count == 0 %>
</p>
<% @user.followers.each do |follower| %>
  <%= link_to user_path(follower.id), class: "black-color no-text-decoration",title: follower.name do %>
    <div class="row mt-5">
      <div class="col-md-2 p-2">
        <%= image_tag avatar_url(follower), class: "round-img" %>
      </div>
      <div class="col-md-10 p-2">
        <p><strong><%= follower.name %></strong></p>
        <p><%= follower.profile_text%></p>
      </div>
    </div>
  <% end %>
<% end %>
  