config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks', 
    registrations:      'registrations', 
  }
  
  devise_scope :user do
    get 'users/password_changes' => 'registrations#password_changes'
  end
  
  # root to: "posts#index"
  root to: "posts#following_posts"
  get      '/users/:id', to: 'users#show', as: 'user'
  
  resources :posts, only: %i(index new create show destroy following_posts) do
    collection do
      get "following_posts"
    end
    resources :photos,   only: %i(create)
    resources :likes,    only: %i(create destroy)
    resources :comments, only: %i(create destroy)
  end
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :relationships, only: %i(create, destroy)
  resources :notifications, only: %i(index)
end

app/views/partial/_circle.html.erb
<%= link_to notifications_path, class: "nav-link" do %>
  <% if unchecked_notifications.any? %>
    通知
    <i class="fas fa-circle n-circle p-1"></i>
  <% else %>
    通知
  <% end %>
<% end %>

app/views/partial/_footer.html.erb
<footer>
  <div class="container my-5">
    <div class="text-center">
      <!--<i class="fa fa-camera" aria-hidden="true">投稿</i>-->
      <%= link_to "", new_post_path, class: "fa fa-camera btn btn-danger btn-lg rounded-circle p-5 m-2"%>
      <p class="p-2">Copyright © Ota</p>
    </div>
  </div>
</footer>

app/views/partial/_navbar.html.erb
<nav class="container navbar navbar-expand-md navbar-light bg-light">
  <a class="navbar-brand" href=<%= root_path %>>Potepan-Insta-Clone</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav ml-auto align-items-md-center">
      <li class="nav-item p-2">
        <%= link_to "HOME", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item p-2">
        <%= link_to "MyPage", user_path(current_user), class: "nav-link" %>
      </li>
      <li class="nav-item p-2">
        <%= render "partial/circle" %>
      </li>
      <li class="nav-item p-2">
        <%= link_to "みんなの投稿", posts_path, class: "nav-link" %>
      </li>
      <li class="nav-item p-2">
        <span class="navbar-text d-flex">
        <%= form_tag(posts_path,:method => 'get') do %>
          <%= text_field_tag :search, "", placeholder: "search...", class: "" %>
          <%= button_tag :caption => nil, :type => "submit", :class =>"btn btn-default btn-s-md" do %>
            <i class="fa fa-search"></i>
          <% end %>
        <% end %>
        </span>
      </li>
    </ul>
  </div>
</nav>