config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks', 
    registrations:      'registrations', 
  }
  
  devise_scope :user do
    get 'users/password_changes' => 'registrations#password_changes'
  end
  
  # root to: "posts#index"
  root to: "posts#following_posts"
  get      '/users/:id', to: 'users#show', as: 'user'
  
  resources :posts, only: %i(index new create show destroy following_posts) do
    collection do
      get "following_posts"
    end
    resources :photos,   only: %i(create)
    resources :likes,    only: %i(create destroy)
    resources :comments, only: %i(create destroy)
  end
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :relationships, only: %i(create, destroy)
  resources :notifications, only: %i(index)
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user,        dependent: :destroy
  has_many :photos,        dependent: :destroy
  has_many :likes,         dependent: :destroy
  has_many :comments,      dependent: :destroy
  has_many :notifications, dependent: :destroy
  
  accepts_nested_attributes_for :photos
  
  validates :caption, length: { maximum: 200 }
  
  def liked_by(user)
    Like.find_by(user_id: user.id, post_id: id)
  end
  
  def self.search(search)
    return Post.all unless search
    Post.where(['caption LIKE ?', "%#{search}%"])
  end
  
  def create_notification_like!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user_id,
        action: 'like'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end
  
  def create_notification_comment!(current_user, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      post_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i(show destroy)
  before_action :set_current_user, only: %i(index following_posts)
  
  def index
    @posts = Post.includes(:photos, :user).order('created_at DESC').search(params[:search]).page(params[:page])
  end
  
  def new
    @post = Post.new
    @post.photos.build
  end

  def create
    @post = Post.new(post_params)
    if @post.photos.present?
      @post.save
      redirect_to root_path
      flash[:notice] = "投稿が保存されました"
    else
      redirect_to new_post_path
      flash[:alert] = "投稿に失敗しました"
    end
  end
  
  def show
  end
  
  def destroy
    if @post.user == current_user
      flash[:notice] = "投稿が削除されました" if @post.destroy
    else
      flash[:alert] = "投稿の削除に失敗しました"
    end
    redirect_to root_path
  end
  
  def following_posts
    @users_ids = [@user.id]
    @users = @user.following
    @users.each do |user|
      @users_ids << user.id
    end
    @posts = Post.includes(:photos, :user).where(user_id: @users_ids).order('created_at DESC').search(params[:search]).page(params[:page])
  end

  private
    def post_params
      params.require(:post).permit(:caption,photos_attributes: [:image]).merge(user_id: current_user.id)
    end
    
    def set_post
      @post = Post.find_by(id: params[:id])
    end
    
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment_list.html.erb
<% post.comments.each do |comment| %>
  <div class="mb-2">
    <% if comment.user == current_user %>
      <%= link_to "", post_comment_path(post.id, comment), method: :delete, remote: true, class: "delete-comment" %>
    <% end %>
    <span>
      <strong>
        <%= link_to comment.user.user_name, user_path(comment.user), class: "no-text-decoration black-color" %>
      </strong>
    </span>
    <span><%= comment.comment %></span>
  </div>
<% end %>

app/views/posts/_like_text.html.erb
<strong>
  <% likes.each.with_index do |like, index| %>
    <% if likes.size == 1 %>
      <%= like.user.user_name %> </strong> が「いいね！」しました
    <% elsif like == likes.last %>
      </strong>と<strong>
      <%= + like.user.user_name %></strong> が「いいね！」しました
    <% elsif index > 1 %>
      </strong><%= "と " + (likes.size-index).to_s + " 他 " %> が「いいね！」しました
      <% break %>
    <% elsif index == likes.size-2 || index == 1 %>
      <%= like.user.user_name %>
    <% else %>
      <%= like.user.user_name + ", " %>
    <% end %>
  <% end %>
</strong>

app/views/posts/_post.html.erb
<div class="container">
  <%= paginate @posts %>
  <div class="row">
    <% @posts.each do |post| %>
    
      <div class="card-wrap col-md-4">
        <div class="card">
          <%= link_to(post_path(post),:data => {:toggle=>"modal", :target => "#exampleModal-#{post.id}" }) do %>
            <%= image_tag post.photos.first.image.url(:medium), class: "card-img-top" %>
          <% end %>
        </div>
      </div>
      
      <!▼モーダル--------------------------->
      <div class="modal fade" id="exampleModal-<%= post.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="card-wrap col-md-12 p-2">
              <div class="card">
                <div class="card-header align-items-center d-flex">
                  <%= link_to user_path(post.user), class: "no-text-decoration" do %>
                    <%= image_tag avatar_url(post.user), class: "post-profile-icon" %>
                  <% end %>
                  <%= link_to user_path(post.user), class: "black-color no-text-decoration",title: post.user.user_name do %>
                    <strong><%= post.user.user_name %></strong>
                  <% end %>
                  
                  <% if post.user_id == current_user.id %>
                    <%= link_to post_path(post), method: :delete, class: "ml-auto mx-0 my-auto" do %>
                      <div class="delete-post-icon">
                      </div>
                    <% end %>
                  <% end %>
                </div>
                <%= image_tag post.photos.first.image.url(:medium), class: "card-img-top" %>
                <div class="card-body">
                  <div class="row parts">
                    <div id="like-icon-post-<%= post.id.to_s %>">
                      <% if post.liked_by(current_user).present? %>
                        <%= link_to "いいねを取り消す", post_like_path(post.id, post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" %>
                      <% else %>
                        <%= link_to "いいね", post_likes_path(post), method: :POST, remote: true, class: "love hide-text" %>
                      <% end %>
                    </div>
                    <%= link_to "", "#", class: "comment" %>
                  </div>
                  <div id="like-text-post-<%= post.id.to_s %>">
                    <%= render "posts/like_text", { likes: post.likes } %>
                  </div>
                  <div>
                    <span><strong><%= post.user.user_name %></strong></span>
                    <span><%= post.caption %></span>
                    <%= link_to time_ago_in_words(post.created_at).upcase + "前", "#", class: "post-time no-text-decoration" %>
                    <div id="comment-post-<%= post.id.to_s %>">
                      <%= render 'posts/comment_list', { post: post } %>
                    </div>
                    <%= link_to time_ago_in_words(post.created_at).upcase + "前", post_path(post),
                      class: "light-color post-time no-text-decoration" %>
                    <hr>
                    <div class="row actions" id="comment-form-post-<%= post.id.to_s %>">
                      <%= form_with model: [post, Comment.new], class: "w-100" do |f| %>
                        <%= f.hidden_field :user_id, value: current_user.id %>
                        <%= f.hidden_field :post_id, value: post.id %>
                        <%= f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント ...", autocomplete: :off %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!▲モーダル------------------->
    <% end %>
  </div>
  <%= paginate @posts %>
</div>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/following_posts.html.erb
<%= render "posts/post" %>

app/views/posts/index.html.erb
<%= render "posts/post" %>

app/views/posts/new.html.erb
<div class="d-flex flex-column align-items-center mt-3">
  <div class="col-xl-7 col-lg-8 col-md-10 col-sm-11 post-card">
    <div class="card">
      <div class="card-header">
        投稿画面
      </div>
      <div class="card-body">
        <%= form_with model: @post, class: "upload-images p-0 border-0" do |f| %>
          <div class="form-group row mt-2">
            <div class="col-auto pr-0">
              <%= image_tag avatar_url(current_user), class: "post-profile-icon" %>
            </div>
            <div class="col pl-0 col align-self-center">
              <%= f.text_field :caption, class: "form-control border-1", placeholder: "投稿内容" %>
            </div>
          </div>
          <div class="mb-3">
            <%= f.fields_for :photos do |i| %>
              <%= i.file_field :image %>
            <% end %>
          </div>
          <%= f.submit "投稿する", class: "btn btn-danger p-1" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="col-md-10 col-md-offset-1 mx-auto postShow-wrap">
  <div class="row post-wrap">
    <div class="col-md-8">
      <div class="card-left">
        <%= image_tag @post.photos.first.image.url(:medium), class: "card-img-top" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card-right">
        <div class="card-right-comment">
          <div class="card-right-name">
            <%= link_to user_path(@post.user), class: "no-text-decoration" do %>
              <%= image_tag avatar_url(@post.user), class: "post-profile-icon" %>
            <% end %>
            <%= link_to user_path(@post.user), class: "black-color no-text-decoration post-user-name",
              title: @post.user.user_name do %>
              <strong><%= @post.user.user_name %></strong>
            <% end %>
          </div>
          <div class="m-2">
            <strong>
              <%= @post.caption %>
            </strong>
          </div>
          <div class="comment-post-id">
            <div class="m-2">
            </div>
          </div>
        </div>
        <div class="row parts">
          <div id="like-icon-post-<%= @post.id.to_s %>">
            <% if @post.liked_by(current_user).present? %>
              <%= link_to "いいねを取り消す", post_like_path(@post.id, @post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" %>
            <% else %>
              <%= link_to "いいね", post_likes_path(@post), method: :POST, remote: true, class: "love hide-text" %>
            <% end %>
          </div>
          <%= link_to "", "#", class: "comment" %>
        </div>
        <div id="like-text-post-<%= @post.id.to_s %>">
          <%= render "posts/like_text", { likes: @post.likes } %>
        </div>
        <div>
          <span><strong><%= @post.user.user_name %></strong></span>
          <span><%= @post.caption %></span>
          <%= link_to time_ago_in_words(@post.created_at).upcase + "前", "#", class: "post-time no-text-decoration" %>
          <div id="comment-post-<%= @post.id.to_s %>">
            <%= render 'posts/comment_list', { post: @post } %>
          </div>
          <%= link_to time_ago_in_words(@post.created_at).upcase + "前", post_path(@post),
            class: "light-color post-time no-text-decoration" %>
          <hr>
          <div class="row actions" id="comment-form-post-<%= @post.id.to_s %>">
            <%= form_with model: [@post, Comment.new], class: "w-100" do |f| %>
              <%= f.hidden_field :user_id, value: current_user.id %>
              <%= f.hidden_field :post_id, value: @post.id %>
              <%= f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント ...", autocomplete: :off %>
            <% end %>
          </div>
        </div>
        <hr>
      </div>
    </div>
  </div>
</div>